// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz4CKh0Z-GOJw0cEWBu4X464Uph6T9nk4',
    appId: '1:415569948772:web:1c4b2f40181e3971ebaf71',
    messagingSenderId: '415569948772',
    projectId: 'hs-flower',
    authDomain: 'hs-flower.firebaseapp.com',
    storageBucket: 'hs-flower.firebasestorage.app',
    measurementId: 'G-6K7Z672NQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgpOm7TAfqbH0X_dbKB8ANliaY5mG5lEw',
    appId: '1:415569948772:android:316661d88e58c342ebaf71',
    messagingSenderId: '415569948772',
    projectId: 'hs-flower',
    storageBucket: 'hs-flower.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdfabk_0uWfWqFYOlaYyva94EVPQ7eFC4',
    appId: '1:415569948772:ios:886d93d38f7688e9ebaf71',
    messagingSenderId: '415569948772',
    projectId: 'hs-flower',
    storageBucket: 'hs-flower.firebasestorage.app',
    iosBundleId: 'com.example.hsFlower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdfabk_0uWfWqFYOlaYyva94EVPQ7eFC4',
    appId: '1:415569948772:ios:886d93d38f7688e9ebaf71',
    messagingSenderId: '415569948772',
    projectId: 'hs-flower',
    storageBucket: 'hs-flower.firebasestorage.app',
    iosBundleId: 'com.example.hsFlower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz4CKh0Z-GOJw0cEWBu4X464Uph6T9nk4',
    appId: '1:415569948772:web:fd278b94b885fdaaebaf71',
    messagingSenderId: '415569948772',
    projectId: 'hs-flower',
    authDomain: 'hs-flower.firebaseapp.com',
    storageBucket: 'hs-flower.firebasestorage.app',
    measurementId: 'G-DEC272M3TG',
  );
}
